### ISSUE TITLE
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not NoneType

### ISSUE THREAD

**Issue by wujun** [harvardnlp/annotated-transformer#102]
I want to train the simple copy task, but get the error in run_epoch function(My computer is macbookpro without cpu and PyTorch is 1.12.1, NumPy is 1.23.1), 
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/xxx/Workspace/transformer-01/main.py", line 39, in <module>
    example_simple_model()
  File "/Users/xxx/Workspace/transformer-01/train.py", line 136, in example_simple_model
    run_epoch(
  File "/Users/xxx/Workspace/transformer-01/train.py", line 168, in run_epoch
    out = model.forward(batch.src, batch.tgt, batch.src_mask, batch.tgt_mask)
  File "/Users/xx/Workspace/transformer-01/model.py", line 31, in forward
    return self.decode(self.encode(src, src_mask), src_mask, tgt, tgt_mask)
  File "/Users/xxx/Workspace/transformer-01/model.py", line 34, in encode
    return self.encoder(self.src_embed(src), src_mask)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/xxx/Workspace/transformer-01/model.py", line 62, in forward
    x = layer(x, mask)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/xxx/Workspace/transformer-01/model.py", line 106, in forward
    x = self.sublayer[0](x, lambda x: self.self_attn(x, x, x, mask))
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/xxx/Workspace/transformer-01/model.py", line 92, in forward
    return x + self.dropout(sublayer(self.norm(x)))
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/dropout.py", line 58, in forward
    return F.dropout(input, self.p, self.training, self.inplace)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/functional.py", line 1252, in dropout
    return _VF.dropout_(input, p, training) if inplace else _VF.dropout(input, p, training)
TypeError: dropout(): argument 'input' (position 1) must be Tensor, not NoneType
python-BaseException

model and train file is ziped and attached. thanks 

[train.py.zip](https://github.com/harvardnlp/annotated-transformer/files/9682339/train.py.zip)

**Comment by wujun** [comment]
My fault, I missed several lines in the model.
