### ISSUE TITLE
on the section of 'Greedy Decoding', got a problem

### ISSUE THREAD

**Issue by jwc19890114** [harvardnlp/annotated-transformer#29]
>Traceback (most recent call last):
  File "C:/Users/01/Desktop/机器学习作业/AllenNLP/test.py", line 632, in <module>
    train_epoch(data_gen(V, 30, 20), model, criterion, model_opt)
  File "C:/Users/01/Desktop/机器学习作业/AllenNLP/test.py", line 589, in train_epoch
    out = model.forward(src, trg[:, :-1], src_mask, trg_mask[:, :-1, :-1])
  File "C:/Users/01/Desktop/机器学习作业/AllenNLP/test.py", line 42, in forward
    return self.decode(self.encode(src, src_mask), src_mask, tgt, tgt_mask)
  File "C:/Users/01/Desktop/机器学习作业/AllenNLP/test.py", line 36, in encode
    return self.encoder(self.tgt_embed(src), src_mask)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\container.py", line 91, in forward
    input = module(input)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:/Users/01/Desktop/机器学习作业/AllenNLP/test.py", line 319, in forward
    return self.lut(x) * math.sqrt(self.d_model)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\modules\sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\ProgramData\Anaconda3\envs\python36\lib\site-packages\torch\nn\functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CPUIntTensor instead (while checking arguments for embedding)

When I using the Colab, I got the correct result.
But on my own Pycharm,  I got this problem. 
Thx, this model is new to me.

**Comment by blmoistawinde** [comment]
I had the same problem, and I've now found [this fix](https://github.com/ictnlp-wshugen/annotated-transformer_codes/commit/ffe3bcc2665fbe5a7f1d53ca8819b1a455903cb8) that works for me
